import { ref } from "vue";

export const useMembers = () => {
  const data = ref([
    {
      id: 1,
      name: "Alex",
      email: "alex@example.com",
      age: 21,
      salary: "8000",
      position: "Accountant",
      surety: "Someone",
      suretyDocument: "/documents/alex_surety.pdf",
      educationalDocument: "/documents/alex_edu.pdf",
      status: "Individual",
      codeNumber: "we234iow",
    },
    {
      id: 2,
      name: "Sophia",
      email: "sophia@example.com",
      age: 28,
      salary: "12000",
      position: "Software Engineer",
      surety: "James",
      suretyDocument: "/documents/sophia_surety.pdf",
      educationalDocument: "/documents/sophia_edu.pdf",
      status: "Branch",
      codeNumber: "mk789xyz",
    },
    {
      id: 3,
      name: "Michael",
      email: "michael@example.com",
      age: 35,
      salary: "15000",
      position: "Project Manager",
      surety: "David",
      suretyDocument: "/documents/michael_surety.pdf",
      educationalDocument: "/documents/michael_edu.pdf",
      status: "Individual",
      codeNumber: "pq456jkl",
    },
    {
      id: 4,
      name: "Emma",
      email: "emma@example.com",
      age: 26,
      salary: "9500",
      position: "Marketing Specialist",
      surety: "Olivia",
      suretyDocument: "/documents/emma_surety.pdf",
      educationalDocument: "/documents/emma_edu.pdf",
      status: "Branch",
      codeNumber: "lm123opq",
    },
    {
      id: 5,
      name: "Daniel",
      email: "daniel@example.com",
      age: 30,
      salary: "11000",
      position: "HR Manager",
      surety: "John",
      suretyDocument: "/documents/daniel_surety.pdf",
      educationalDocument: "/documents/daniel_edu.pdf",
      status: "Individual",
      codeNumber: "xy987rst",
    },
    {
      id: 6,
      name: "Liam",
      email: "liam@example.com",
      age: 32,
      salary: "13500",
      position: "Operations Manager",
      surety: "Noah",
      suretyDocument: "/documents/liam_surety.pdf",
      educationalDocument: "/documents/liam_edu.pdf",
      status: "Branch",
      codeNumber: "ab123cde",
    },
    {
      id: 7,
      name: "Ava",
      email: "ava@example.com",
      age: 27,
      salary: "9000",
      position: "Sales Representative",
      surety: "Mason",
      suretyDocument: "/documents/ava_surety.pdf",
      educationalDocument: "/documents/ava_edu.pdf",
      status: "Individual",
      codeNumber: "gh789ijk",
    },
    {
      id: 8,
      name: "Ethan",
      email: "ethan@example.com",
      age: 29,
      salary: "12500",
      position: "Financial Analyst",
      surety: "William",
      suretyDocument: "/documents/ethan_surety.pdf",
      educationalDocument: "/documents/ethan_edu.pdf",
      status: "Branch",
      codeNumber: "st456uvw",
    },
    {
      id: 9,
      name: "Mia",
      email: "mia@example.com",
      age: 24,
      salary: "8500",
      position: "Graphic Designer",
      surety: "Sophia",
      suretyDocument: "/documents/mia_surety.pdf",
      educationalDocument: "/documents/mia_edu.pdf",
      status: "Individual",
      codeNumber: "mn234opq",
    },
    {
      id: 10,
      name: "Benjamin",
      email: "benjamin@example.com",
      age: 31,
      salary: "14000",
      position: "Team Lead",
      surety: "Daniel",
      suretyDocument: "/documents/benjamin_surety.pdf",
      educationalDocument: "/documents/benjamin_edu.pdf",
      status: "Branch",
      codeNumber: "qr567xyz",
    },
  ]);

  return { data };
};
